import { LAYOUT_APP, LAYOUT_AUTH } from '../../shared/layout';

export const routes = [
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Sign in',
    path: '/',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userLogin' */ './view/login'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Sign in',
    path: '/login',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userLogin' */ './view/login'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Sign up',
    path: '/registration',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userRegistration' */ './view/registration'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: false,
    name: 'New password',
    path: '/password-recovery/:token',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userPasswordRecovery' */ './view/passwordRecovery'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'New password',
    path: '/password-recovery',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userPasswordRecovery' */ './view/passwordRecovery'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Reset your password',
    path: '/password-reset',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userPasswordRecovery' */ './view/passwordReset'),
    resolvers: [],
  },
  {
    layout: LAYOUT_APP,
    exact: true,
    name: 'Profile',
    path: '/profile',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userProfile'  */ './view/profile'),
    resolvers: [],
  },
];
